// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221123030538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Model.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Data.Model.Etape", b =>
                {
                    b.Property<int>("EtapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtapeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRecette")
                        .HasColumnType("int");

                    b.Property<int>("RecetteId")
                        .HasColumnType("int");

                    b.Property<int>("TempsEtape")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtapeId");

                    b.HasIndex("RecetteId");

                    b.ToTable("Etapes");
                });

            modelBuilder.Entity("Data.Model.Recette", b =>
                {
                    b.Property<int>("RecetteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetteId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeRecette")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionRecette")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreRecette")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecetteId");

                    b.HasIndex("CategorieId");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("Data.Model.Etape", b =>
                {
                    b.HasOne("Data.Model.Recette", "recette")
                        .WithMany()
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recette");
                });

            modelBuilder.Entity("Data.Model.Recette", b =>
                {
                    b.HasOne("Data.Model.Categorie", "categorie")
                        .WithMany("Recettes")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });

            modelBuilder.Entity("Data.Model.Categorie", b =>
                {
                    b.Navigation("Recettes");
                });
#pragma warning restore 612, 618
        }
    }
}
